### ISSUE TITLE
Add basic id and classes to separate sections

### ISSUE THREAD

**Issue by mustafa-ahmed394** [baber-khan/Muscle-Power#5]
Add basic CSS to make the sections.

**Comment by baber-khan** [comment]
Updates?

**Comment by mustafa-ahmed394** [comment]
@baber-khan  hogaya tha ye. reopen kyun kiya?

**Comment by mustafa-ahmed394** [comment]
sorry about that. wrong button.

**Comment by baber-khan** [comment]
Yep, Done hogaya tou close kardou isko.
